import {types, addType} from 'goblin-gadgets/types/types.js';
import PropTypes from 'prop-types';

const samples = [
  {id: 'team', text: 'Collaborateurs'},
  {id: 'colors', text: 'Couleurs'},
  {id: 'months', text: 'Mois'},
  {id: 'transports', text: 'Moyens de transport'},
  {id: 'localities', text: 'Localités'},
  {id: 'strange', text: 'Bizarre'},
  {id: 'multiline', text: 'Multiligne'},
];

const samplesList = {
  team: [
    'Ernest',
    'Marie-Antoinette',
    'Jean-Pierre',
    'Nicole',
    'Sandra',
    'Marc-Antoine',
    'Sophie',
  ],
  colors: [
    {id: 'R', text: 'Rouge'},
    {id: 'G', text: 'Vert'},
    {id: 'B', text: 'Bleu'},
  ],
  months: [
    {id: '1', text: 'Janvier'},
    {id: '2', text: 'Février'},
    {id: '3', text: 'Mars'},
    {id: '4', text: 'Avril'},
    {id: '5', text: 'Mai'},
    {id: '6', text: 'Juin'},
    {id: '7', text: 'Juillet'},
    {id: '8', text: 'Août'},
    {id: '9', text: 'Septembre'},
    {id: '10', text: 'Octobre'},
    {id: '11', text: 'Novembre'},
    {id: '12', text: 'Décembre'},
  ],
  transports: [
    {id: 'bike', text: 'Vélo', glyph: 'solid/bicycle'},
    {id: 'car', text: 'Voiture', glyph: 'solid/car'},
    {id: 'rocket', text: 'Fusée super-sonique', glyph: 'solid/rocket'},
  ],
  localities: [
    'Allaman',
    'Avanche',
    'Berne',
    'Belmont',
    'Bienne',
    'Boudry',
    'Brig',
    'Chamblon',
    'Cheseaux',
    'Chexbres',
    'Crissier',
    'Cortaillod',
    'Delémont',
    'Echallens',
    'Fribourg',
    'Genève',
    'Granson',
    'Jouxtens',
    'La Brévine',
    'La Chaux-de-Fonds',
    'La Sarraz',
    'Lausanne',
    'Le Locle',
    'Les Breuleux',
    'Martigny',
    'Montreux',
    'Neuchâtel',
    'Nyon',
    'Paudex',
    'Prilly',
    'Pully',
    'Renens',
    'Rolle',
    'Sainte-Croix',
    'Sierre',
    'Sion',
    'Soleure',
    'St. Maurice',
    'Ursy',
    'Vevey',
    'Villeneuve',
    'Yverdon-les-Bains',
    'Winthertur',
    'Zurich',
  ],
  strange: [
    'Allaman',
    'Avanche',
    'Cortaillod',
    'Genève',
    'Jouxtens',
    'La Brévine',
    {id: 'chx-fds', text: 'La Chaux-de-Fonds', glyph: 'solid/rocket'},
    'Lausanne',
    'Le Locle',
    'Neuchâtel',
    'Pully',
    'Renens',
    'Rolle',
    'Sion',
    'Soleure',
    'St. Maurice',
    "Un jeune vieillard, assis debout sur un mur de pierre en bois, lisait un journal plié en quatre dans sa poche, à la lueur d'une bougie éteinte.",
    'Vevey',
    'Villeneuve',
    'Yverdon-les-Bains',
    'Zurich',
  ],
  multiline: [
    'Ligne 1\nLigne 2\nLigne 3',
    'A\nB\nC',
    'Samedi\nDimanche',
    'Tralala',
    'Ligne 1\nLigne 2\nLigne 3\nLigne 4\nLigne 5',
    'Fin',
  ],
};

/******************************************************************************/

addType('dataList', {
  type: 'dataList',
  defaultValue: 'T1',
  widget: 'combo',
  readonly: true,
  samples: samples,
  samplesData: samplesList,
  propType: PropTypes.object,
});

/******************************************************************************/

export default [
  {
    name: 'onChange',
    group: 'event',
    type: types.function,
  },
  {
    name: 'onShowCombo',
    group: 'event',
    type: types.function,
  },
  {
    name: 'readonly',
    group: 'text',
    type: types.bool,
  },
  {
    name: 'restrictsToList',
    group: 'text',
    type: types.bool,
  },
  {
    name: 'list',
    group: 'menu',
    type: types.dataList,
    required: true,
  },
  {
    name: 'selectedId',
    group: 'text',
    type: types.string,
  },
  {
    name: 'menuType',
    group: 'menu',
    type: types.enum(['', 'menu', 'wrap']),
  },
  {
    name: 'flyingBalloonAnchor',
    group: 'menu',
    type: types.enum(['', 'top', 'bottom', 'left', 'right']),
  },
  {
    name: 'shape',
    group: 'aspect',
    type: types.shape,
  },
  {
    name: 'hintText',
    group: 'text',
    type: types.nabu,
  },
  {
    name: 'tooltip',
    group: 'aspect',
    type: types.nabu,
  },
  {
    name: 'width',
    group: 'layout',
    type: types.size,
  },
  {
    name: 'fieldWidth',
    group: 'layout',
    type: types.size,
  },
  {
    name: 'rows',
    group: 'text',
    type: types.enum(['', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10']),
  },
  {
    name: 'required',
    group: 'aspect',
    type: types.bool,
  },
  {
    name: 'disabled',
    group: 'aspect',
    type: types.bool,
  },
  {
    name: 'visibility',
    group: 'aspect',
    type: types.bool,
  },
  {
    name: 'autoFocus',
    group: 'aspect',
    type: types.bool,
  },
  {
    name: 'selectAllOnFocus',
    group: 'aspect',
    type: types.bool,
  },
  {
    name: 'show',
    group: 'aspect',
    type: types.bool,
  },
  {
    name: 'menuItemWidth',
    group: 'menu',
    type: types.size,
  },
  {
    name: 'menuItemTooltips',
    group: 'menu',
    type: types.bool,
  },
  {
    name: 'comboGlyph',
    group: 'menu',
    type: types.glyph,
  },
  {
    name: 'comboTextTransform',
    group: 'menu',
    type: types.enum(['', 'none']),
  },
  {
    name: 'hideButtonCombo',
    group: 'menu',
    type: types.bool,
  },

  {
    name: 'spacing',
    group: 'layout',
    type: types.spacing,
  },
  {
    name: 'grow',
    group: 'layout',
    type: types.grow,
  },
];
