import Type from 'goblin-gadgets/types/index.js';

export default [
  {
    name: 'children',
    group: 'main',
    type: Type.component,
  },
  {
    name: 'onClick',
    group: 'main',
    type: Type.function,
  },
  {
    name: 'disabled',
    group: 'aspect',
    type: Type.bool,
  },
  {
    name: 'show',
    group: 'aspect',
    type: Type.bool,
  },
  {
    name: 'selected',
    group: 'aspect',
    type: Type.bool,
  },
  {
    name: 'hidden',
    group: 'aspect',
    type: Type.bool,
  },
  {
    name: 'visibility',
    group: 'aspect',
    type: Type.bool,
  },
  {
    name: 'busy',
    group: 'aspect',
    type: Type.bool,
  },
  {
    name: 'isDragged',
    group: 'aspect',
    type: Type.bool,
  },
  {
    name: 'isTransparentWhenDrag',
    group: 'aspect',
    type: Type.bool,
  },
  {
    name: 'hasHeLeft',
    group: 'aspect',
    type: Type.bool,
  },
  {
    name: 'kind',
    group: 'aspect',
    type: Type.enum([
      '',
      'actions',
      'box',
      'boxes',
      'chronos-events',
      'column',
      'column-full',
      'compact-row',
      'content',
      'drag-to-delete',
      'drag-too-many',
      'floating',
      'floating-footer',
      'floating-header',
      'flying-balloon',
      'flying-chat',
      'flying-dialog',
      'footer',
      'full-view',
      'glyph-samples',
      'left-bar',
      'main-tab',
      'main-tab-right',
      'mandats',
      'pane',
      'pane-top',
      'panes',
      'pane-header',
      'pane-header-light',
      'pane-hnavigator',
      'pane-navigator',
      'pane-top',
      'pane-vnavigator',
      'right',
      'row',
      'row-pane',
      'row-pane-drag',
      'row-wrap',
      'second-bar',
      'task-bar',
      'thin-center',
      'thin-column',
      'thin-main',
      'thin-row',
      'ticket-mode',
      'ticket-row',
      'ticket-column',
      'tickets',
      'tickets-desk',
      'tickets-messengers',
      'tickets-messenger',
      'tickets-root',
      'tickets-trips',
      'tickets-tray',
      'top-bar',
      'view',
      'view-edge',
      'view-right',
      'view-stretch',
      'view-tab',
      'view-tab-right',
      'views',
      'wrap',
    ]),
  },
  {
    name: 'cursor',
    group: 'aspect',
    type: Type.cursor,
  },
  {
    name: 'subkind',
    group: 'aspect',
    type: Type.enum([
      '',
      'box',
      'box-left',
      'footer',
      'info',
      'large-box',
      'left',
      'light-box',
      'list',
      'me',
      'no-shadow',
      'top-margin',
      'wide-info',
      'wrap',
    ]),
  },
  {
    name: 'border',
    group: 'aspect',
    type: Type.enum(['', 'top', 'right', 'bottom', 'left']),
  },
  {
    name: 'trianglePosition',
    group: 'aspect',
    type: Type.enum(['', 'top', 'right', 'bottom', 'left', 'none']),
  },
  {
    name: 'triangleShift',
    group: 'aspect',
    type: Type.size,
  },
  {
    name: 'width',
    group: 'Layout',
    type: Type.size,
  },
  {
    name: 'height',
    group: 'Layout',
    type: Type.size,
  },
  {
    name: 'minWidth',
    group: 'Layout',
    type: Type.size,
  },
  {
    name: 'minHeight',
    group: 'Layout',
    type: Type.size,
  },
  {
    name: 'maxWidth',
    group: 'Layout',
    type: Type.size,
  },
  {
    name: 'maxHeight',
    group: 'Layout',
    type: Type.size,
  },
  {
    name: 'verticalJustify',
    group: 'Layout',
    type: Type.enum(['', 'top']),
  },
  {
    name: 'verticalSpacing',
    group: 'Layout',
    type: Type.spacing,
  },
  {
    name: 'marginBottom',
    group: 'Layout',
    type: Type.size,
  },
  {
    name: 'floatingHeight',
    group: 'Layout',
    type: Type.size,
  },
  {
    name: 'grow',
    group: 'Layout',
    type: Type.grow,
  },
  {
    name: 'spacing',
    group: 'Layout',
    type: Type.spacing,
  },
  {
    name: 'backgroundColor',
    group: 'aspect',
    type: Type.color,
  },
  {
    name: 'busyBackgroundColor',
    group: 'aspect',
    type: Type.color,
  },
];
