import Type from 'goblin-gadgets/types/index.js';

export default [
  {
    name: 'text',
    group: 'main',
    type: Type.string,
    description: 'The text of the button',
    required: true,
    defaultValue: '',
  },
  {
    name: 'textColor',
    group: 'aspect',
    type: Type.color,
    defaultValue: '',
  },
  {
    name: 'glyphColor',
    group: 'aspect',
    type: Type.color,
    defaultValue: '',
  },
  {
    name: 'disabled',
    group: 'main',
    type: Type.bool,
    defaultValue: false,
  },
  {
    name: 'kind',
    group: 'aspect',
    type: Type.enum([
      '',
      'big-center',
      'center-to-box',
      'compact',
      'floating-footer',
      'floating-header',
      'flying-balloon',
      'footer',
      'info',
      'large-left',
      'large-right',
      'large-single',
      'notification',
      'one-line-height',
      'pane-header',
      'task',
      'ticket-warning',
      'title',
      'title-recurrence',
    ]),
    description: 'The kind property change the style of the button.',
    defaultValue: '',
  },
  {
    name: 'shape',
    group: 'aspect',
    type: Type.enum([
      '',
      'rounded',
      'left-rounded',
      'right-rounded',
      'left-smooth',
      'right-smooth',
    ]),
    description: 'Change shape of the button.',
    defaultValue: '',
  },
  {
    name: 'active',
    group: 'aspect',
    type: Type.bool,
    defaultValue: false,
  },
  {
    name: 'glyph',
    group: 'aspect',
    type: Type.glyph,
    description: 'Display a glyph before text.',
    defaultValue: '',
  },
];
