export default [
  {
    name: 'default',
    props: {
      size: '200px',
      kind: 'toy',
      disabled: false,
      textColor: '#eee',
      background: 'linear-gradient(180deg, #56b4ff, #9651c6)',
      backgroundHover: 'linear-gradient(180deg, #72d5ea, #a988ed)',
      gaugeColor: '#9651c6',
      startedCount: 3,
      totalCount: 5,
      title: 'Aventure',
      subtitle: 'Décollage',
      glyph: 'solid/rocket',
      iconShadow: true,
    },
  },
  {
    name: 'simple',
    props: {
      size: '100px',
      kind: 'default',
      disabled: false,
      textColor: '#fff',
      background: '#da6c29',
      backgroundHover: '#ef894b',
      gaugeColor: '#333',
      startedCount: 0,
      totalCount: 0,
      title: 'Valider',
      glyph: 'solid/check',
    },
  },
  {
    name: 'crossed',
    props: {
      size: '300px',
      kind: 'default',
      disabled: false,
      textColor: '#fff',
      background: 'linear-gradient(-45deg, #0088ff 50%, #ffaa00 50%)',
      backgroundHover: '#588ceb',
      title: 'Démarrer',
      glyph: 'solid/car',
      crossed: true,
    },
  },
  {
    name: 'overflow',
    props: {
      size: '200px',
      kind: 'default',
      disabled: false,
      textColor: '#fff',
      background: '#2671fa',
      backgroundHover: '#588ceb',
      title: 'Démarrer',
      glyph: 'solid/car',
      gaugeColor: '#2671fa',
      startedCount: 5,
      totalCount: 5,
    },
  },
  {
    name: 'empty',
    props: {},
  },
];
