import Type from 'goblin-gadgets/types/index.js';

export default [
  {
    name: 'text',
    group: 'main',
    type: Type.string,
    description: 'The text of the button',
    required: true,
    defaultValue: '',
  },
  {
    name: 'onClick',
    group: 'main',
    type: Type.function,
  },
  {
    name: 'textColor',
    group: 'aspect',
    type: Type.color,
    defaultValue: '',
  },
  {
    name: 'glyphColor',
    group: 'glyph',
    type: Type.color,
    defaultValue: '',
  },
  {
    name: 'disabled',
    group: 'main',
    type: Type.bool,
    defaultValue: false,
  },
  {
    name: 'kind',
    group: 'aspect',
    type: Type.enum([
      '',
      'action',
      'button-notification',
      'button-footer',
      'calendar',
      'calendar-navigator',
      'check-button',
      'chronos-navigator',
      'chronos-navigator',
      'combo',
      'combo-item',
      'combo-wrap-item',
      'desk-title',
      'disabled-light',
      'dynamic-toolbar-left',
      'dynamic-toolbar-top-left',
      'dynamic-toolbar-top-right',
      'glyph-item',
      'hover',
      'identity',
      'label',
      'main-tab',
      'main-tab-right',
      'menu-item',
      'notification-close',
      'pane-navigator',
      'pane-hnavigator',
      'pane-vnavigator',
      'recurrence',
      'round',
      'subaction',
      'task-bar',
      'task-tab',
      'task-logo',
      'thin-left',
      'thin-right',
      'toolbar',
      'view-tab',
      'view-tab-right',
      'warning',
      'text',
    ]),
    description: 'The kind property change the style of the button.',
    defaultValue: '',
  },
  {
    name: 'glyph',
    group: 'glyph',
    type: Type.glyph,
    description: 'Display a glyph before text.',
    defaultValue: '',
  },
  {
    name: 'active',
    group: 'aspect',
    type: Type.bool,
    defaultValue: false,
  },
  {
    name: 'readonly',
    group: 'aspect',
    type: Type.bool,
    defaultValue: false,
  },
  {
    name: 'focusable',
    group: 'aspect',
    type: Type.bool,
    defaultValue: false,
  },
  {
    name: 'busy',
    group: 'aspect',
    type: Type.bool,
    defaultValue: false,
  },
  {
    name: 'border',
    group: 'aspect',
    type: Type.enum(['', 'none']),
    defaultValue: '',
  },
  {
    name: 'glyphRotate',
    group: 'glyph',
    type: Type.angle,
    defaultValue: '',
  },
  {
    name: 'glyphFlip',
    group: 'glyph',
    type: Type.enum(['', 'horizontal', 'vertical']),
    defaultValue: '',
  },
  {
    name: 'glyphSpin',
    group: 'glyph',
    type: Type.enum(['', 'yes']),
    defaultValue: '',
  },
  {
    name: 'glyphPosition',
    group: 'glyph',
    type: Type.enum(['', 'left', 'right']),
    defaultValue: 'left',
  },
  {
    name: 'glyphSize',
    group: 'glyph',
    type: Type.percentage,
    defaultValue: '',
  },
  {
    name: 'shape',
    group: 'aspect',
    type: Type.shape,
    defaultValue: '',
  },
  {
    name: 'tooltip',
    group: 'aspect',
    type: Type.string,
    field: 'tooltip',
    defaultValue: '',
  },
  {
    name: 'shortcut',
    group: 'aspect',
    type: Type.shortcut,
    defaultValue: '',
  },
  {
    name: 'justify',
    group: 'aspect',
    type: Type.justify,
    defaultValue: '',
  },
  {
    name: 'width',
    group: 'layout',
    type: Type.size,
    defaultValue: '',
  },
  {
    name: 'height',
    group: 'layout',
    type: Type.size,
    defaultValue: '',
  },
  {
    name: 'grow',
    group: 'layout',
    type: Type.grow,
    defaultValue: '',
  },
  {
    name: 'spacing',
    group: 'layout',
    type: Type.spacing,
    defaultValue: '',
  },
  {
    name: 'backgroundColor',
    group: 'aspect',
    type: Type.color,
    defaultValue: '',
  },
  {
    name: 'activeColor',
    group: 'aspect',
    type: Type.color,
    defaultValue: '',
  },
  {
    name: 'fontSize',
    group: 'text',
    type: Type.percentage,
    defaultValue: '',
  },
  {
    name: 'fontWeight',
    group: 'text',
    type: Type.fontWeight,
    defaultValue: '',
  },
  {
    name: 'fontStyle',
    group: 'text',
    type: Type.fontStyle,
    defaultValue: '',
  },
  {
    name: 'textTransform',
    group: 'text',
    type: Type.textTransform,
    defaultValue: '',
  },
  {
    name: 'wrap',
    group: 'text',
    type: Type.enum(['', 'no', 'no-strict', 'yes', 'yes-permissive']),
    defaultValue: '',
  },
  {
    name: 'badgeValue',
    group: 'badge',
    type: Type.enum(['', '1', '2', '99', '123456']),
    defaultValue: '',
  },
  {
    name: 'badgePush',
    group: 'badge',
    type: Type.bool,
    defaultValue: '',
  },
  {
    name: 'place',
    group: 'aspect',
    type: Type.enum(['', '1/1', '1/3', '2/3', '3/3']),
    defaultValue: '',
  },
  {
    name: 'calendarWeekend',
    group: 'calendar',
    type: Type.bool,
    defaultValue: false,
  },
  {
    name: 'calendarDimmed',
    group: 'calendar',
    type: Type.bool,
    defaultValue: false,
  },
  {
    name: 'cursor',
    group: 'aspect',
    type: Type.cursor,
    defaultValue: '',
  },
  {
    name: 'show',
    group: 'aspect',
    type: Type.bool,
    defaultValue: true,
  },
  {
    name: 'visibility',
    group: 'aspect',
    type: Type.bool,
    defaultValue: true,
  },
];
